name: recipe_book
description: A personal recipe cookbook.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  #UI
  cached_network_image: ^3.2.2
  image_picker: ^0.8.5+3
  shimmer: ^2.0.0
  flutter_svg: ^1.1.5
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
    
  #Local packages
  firebase_recipes_api:
    path: packages/recipes/firebase_recipes_api
  recipes_api:
    path: packages/recipes/recipes_api
  recipes_repository:
    path: packages/recipes/recipes_repository
  auth_api:
    path: packages/auth/auth_api
  auth_repository:
    path: packages/auth/auth_repository
  
  #Firebase
  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0
  firebase_storage: ^10.3.10

  #BLoC
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svgs/
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
