name: recipe_book
description: A personal recipe cookbook.

publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #UI
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
    
  #Local packages
  firebase_recipes_api:
    path: packages/recipes/firebase_recipes_api
  recipes_api:
    path: packages/recipes/recipes_api
  recipes_repository:
    path: packages/recipes/recipes_repository
  firebase_auth_api:
    path: packages/auth/firebase_auth_api
  auth_api:
    path: packages/auth/auth_api
  auth_repository:
    path: packages/auth/auth_repository
  
  #Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0

  #BLoC
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  accessibility_tools: ^2.2.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svgs/
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
