name: auth_repository
description: Repository that handles auth related requests.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_auth: ^5.1.1
  auth_api:
    path: ../auth_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
