name: firebase_recipes_api
description: Implementation of RecipesApi using Firebase 
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.3
  rxdart: ^0.27.5
  uuid: ^3.0.6
  recipes_api:
    path: ../recipes_api

dev_dependencies:
  flutter_lints: ^2.0.0
  