name: firebase_recipes_api
description: Implementation of RecipesApi using Frirebase 
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^3.4.9
  rxdart: ^0.27.5
  recipes_api:
    path: ../recipes_api

dev_dependencies:
  flutter_lints: ^2.0.0
  