name: auth_api
description: Interface and models for an API providing authorization/authentication.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
